package handlers

import (
	"context"
	"net/http"

	"technik-server/database"
	"technik-server/dto"
	"technik-server/middleware"
	"technik-server/prisma/db"

	"github.com/gin-gonic/gin"
	"github.com/pquerna/otp/totp"
	qrcode "github.com/skip2/go-qrcode"
)

// validateTOTPCode checks a 6-digit authenticator app code against a stored
// base32 TOTP secret using the standard 30s/SHA1/6-digit parameters.
func validateTOTPCode(secret, code string) bool {
	if secret == "" || code == "" {
		return false
	}
	return totp.Validate(code, secret)
}

// GetMfaSetupQR generates a fresh TOTP secret for the school, stores it, and
// responds with a scannable QR code (PNG) encoding the otpauth:// URI.
// Requires the short-lived "mfa-setup" purpose token minted at activation
// time, so this can't be triggered by knowing the email alone.
func (h *AuthHandler) GetMfaSetupQR(c *gin.Context) {
	email := c.Query("email")
	actToken := c.Query("actToken")

	if email == "" || actToken == "" {
		c.JSON(http.StatusBadRequest, dto.APIError{Success: false, Error: "email and actToken are required"})
		return
	}

	claims, err := middleware.ValidatePurposeToken(actToken, "mfa-setup", h.cfg.JWTSecret)
	if err != nil || claims.Email != email {
		c.JSON(http.StatusUnauthorized, dto.APIError{Success: false, Error: "This MFA setup link is invalid or has expired. Please log in again to restart activation."})
		return
	}

	ctx := context.Background()
	school, err := database.Client.SchoolDetails.FindUnique(
		db.SchoolDetails.Email.Equals(email),
	).Exec(ctx)

	if err != nil || school == nil {
		c.JSON(http.StatusNotFound, dto.APIError{Success: false, Error: "School not found"})
		return
	}

	key, err := totp.Generate(totp.GenerateOpts{
		Issuer:      "Technik Olympiad",
		AccountName: email,
	})
	if err != nil {
		c.JSON(http.StatusInternalServerError, dto.APIError{Success: false, Error: "Failed to generate authenticator secret"})
		return
	}

	_, err = database.Client.SchoolDetails.FindUnique(
		db.SchoolDetails.ID.Equals(school.ID),
	).Update(
		db.SchoolDetails.MsAuthSecret.Set(key.Secret()),
	).Exec(ctx)

	if err != nil {
		c.JSON(http.StatusInternalServerError, dto.APIError{Success: false, Error: "Failed to store authenticator secret"})
		return
	}

	png, err := qrcode.Encode(key.String(), qrcode.Medium, 256)
	if err != nil {
		c.JSON(http.StatusInternalServerError, dto.APIError{Success: false, Error: "Failed to generate QR code"})
		return
	}

	c.Data(http.StatusOK, "image/png", png)
}

// VerifyMfaSetup confirms the code the school entered from their
// authenticator app matches the secret generated by GetMfaSetupQR, and only
// then marks MFA (TwoFactorEnable) as enabled.
func (h *AuthHandler) VerifyMfaSetup(c *gin.Context) {
	var req dto.MfaVerifySetupRequest
	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, dto.APIError{Success: false, Error: err.Error()})
		return
	}

	claims, err := middleware.ValidatePurposeToken(req.ActToken, "mfa-setup", h.cfg.JWTSecret)
	if err != nil || claims.Email != req.Email {
		c.JSON(http.StatusUnauthorized, dto.APIError{Success: false, Error: "This MFA setup link is invalid or has expired. Please log in again to restart activation."})
		return
	}

	ctx := context.Background()
	school, err := database.Client.SchoolDetails.FindUnique(
		db.SchoolDetails.Email.Equals(req.Email),
	).Exec(ctx)

	if err != nil || school == nil {
		c.JSON(http.StatusNotFound, dto.APIError{Success: false, Error: "School not found"})
		return
	}

	secret, hasSecret := school.MsAuthSecret()
	if !hasSecret || secret == "" || !validateTOTPCode(secret, req.Code) {
		c.JSON(http.StatusBadRequest, dto.APIError{Success: false, Error: "Invalid authenticator code. Please try again."})
		return
	}

	_, err = database.Client.SchoolDetails.FindUnique(
		db.SchoolDetails.ID.Equals(school.ID),
	).Update(
		db.SchoolDetails.TwoFactorEnable.Set(true),
	).Exec(ctx)

	if err != nil {
		c.JSON(http.StatusInternalServerError, dto.APIError{Success: false, Error: "Failed to enable Microsoft Authenticator"})
		return
	}

	c.JSON(http.StatusOK, gin.H{
		"success": true,
		"message": "Microsoft Authenticator has been enabled for your account.",
	})
}

// GetMfaStatus reports whether Microsoft Authenticator has already been
// configured for the given email, so the Code Verification screen knows
// which verification options to offer.
func (h *AuthHandler) GetMfaStatus(c *gin.Context) {
	email := c.Query("email")
	if email == "" {
		c.JSON(http.StatusBadRequest, dto.APIError{Success: false, Error: "email is required"})
		return
	}

	ctx := context.Background()
	school, err := database.Client.SchoolDetails.FindUnique(
		db.SchoolDetails.Email.Equals(email),
	).Exec(ctx)

	if err != nil || school == nil {
		c.JSON(http.StatusNotFound, dto.APIError{Success: false, Error: "School not found"})
		return
	}

	c.JSON(http.StatusOK, dto.MfaStatusResponse{
		Success:       true,
		MsAuthEnabled: school.TwoFactorEnable,
		Email:         school.Email,
	})
}
